### ISSUE TITLE
Any chance of port to JetBrains? 

### ISSUE THREAD

**Issue by svintit** [dillonchanis/theme-midnight-city#12]
Love this theme so much, I've recently moved to RubyMine as starting in a new company, and I'd love to use this theme. Just a thought, as the theme would then be available for all JetBrains products.

**Comment by dillonchanis** [comment]
Hey @svintit glad you like it! I've never thought about porting it elsewhere since 99% of the time I'm in VSCode. However, if you wanted to give it a shot porting over to JetBrains I don't mind at all! I'd even link to it from here in case any others were interested.

If you wanted to try I'd take a look over at [Dracula's repo](https://github.com/dracula/jetbrains/tree/master) -- it's what I used to get started with this a few years back. You can grab the colors I used from `src/midnight-city.yml`

**Comment by svintit** [comment]
Hey @dillonchanis, so I did end up making something pretty similar, but I wasn't very picky about specifics (though the colours do match, see line number colour for example) to get it to match 100%, so probably not worth sharing without more work put into it.

Thanks so much for the inspiration at least!

<img width="880" alt="image" src="https://user-images.githubusercontent.com/44262998/174902956-ef752153-865e-4098-9b22-ba83e9489eff.png">
